version: 2
updates:
  # Maintain dependencies for npm/yarn
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    versioning-strategy: 'auto'
    labels:
      - 'dependencies'
      - 'security'
    # Group all minor and patch updates into a single PR
    groups:
      minor-patch-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    # Automatically assign reviewers
    assignees:
      - '${{github.actor}}'
    allow:
      # Explicitly allow updates for @nestjs packages to catch the fix when available
      - dependency-name: '@nestjs/*'

  # Keep actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'github-actions'
