version: '3.8'

services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: unless-stopped
    ports:
      - '8086:8086'
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXD_HTTP_BIND_ADDRESS=0.0.0.0:8086
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - xdc-monitor-network

  xdc-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xdc-monitor
    restart: on-failure:5
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs:rw
      - ./dist:/app/dist:ro
    environment:
      - NODE_ENV=production
      - INFLUXDB_URL=http://influxdb:8086
    networks:
      - xdc-monitor-network
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - .env
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana_data/config/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana_data/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana_data/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana_data/provisioning/plugins:/etc/grafana/provisioning/plugins:ro
      - ./grafana_data/provisioning/alerting:/etc/grafana/provisioning/alerting:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_PROVISIONING=true
    networks:
      - xdc-monitor-network
    depends_on:
      - influxdb

networks:
  xdc-monitor-network:
    driver: bridge

volumes:
  influxdb-storage:
  grafana-storage:
