version: '3.8'

services:
  xdc-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xdc-monitor
    restart: unless-stopped
    ports:
      - '3000:3000' # Application port
      - '9090:9090' # Metrics endpoint
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./dist:/app/dist
    networks:
      - xdc-monitor-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    # Using nobody user to match file permissions
    user: '65534:65534' # nobody:nobody
    ports:
      - '9091:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.wal-compression'
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'
    networks:
      - xdc-monitor-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - .env
    volumes:
      # Runtime data - not version controlled
      - grafana_data_volume:/var/lib/grafana/data
      - grafana_logs_volume:/var/lib/grafana/logs
      - grafana_plugins_volume:/var/lib/grafana/plugins
      # Configuration - version controlled
      - ./grafana_config/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana_config/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana_config/provisioning/plugins:/etc/grafana/provisioning/plugins
      - ./grafana_config/provisioning/alerting:/etc/grafana/provisioning/alerting
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_PROVISIONING=true
    networks:
      - xdc-monitor-network
    depends_on:
      - prometheus

networks:
  xdc-monitor-network:
    driver: bridge

volumes:
  grafana_data_volume:
  grafana_logs_volume:
  grafana_plugins_volume:
