global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Storage retention is configured via command line flags in docker-compose.yml, not here

scrape_configs:
  - job_name: 'xdc-monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['xdc-monitor:3000']
        labels:
          service: 'xdc-monitor'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          service: 'prometheus'
