{
 "title": "XDC Internal Monitoring",
 "description": "Main dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"host\""
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "50, 75, 95, 99, 999, 9999" },
   { "name": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "system",
       "expr": "system_cpu_sysload",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "system",
       "measurement": "geth.system/cpu/sysload.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "iowait",
       "expr": "system_cpu_syswait",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "iowait",
       "measurement": "geth.system/cpu/syswait.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "geth",
       "expr": "system_cpu_procload",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "geth",
       "measurement": "geth.system/cpu/procload.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "alloc",
       "expr": "system_cpu_sysload",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "system",
       "measurement": "geth.system/memory/allocs.meter",
       "select": [
        [
         { "params": [ "m1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "used",
       "expr": "system_cpu_syswait",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "iowait",
       "measurement": "geth.system/memory/used.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "held",
       "expr": "system_cpu_procload",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "geth",
       "measurement": "geth.system/memory/held.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "read",
       "expr": "rate(system_disk_readbytes[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "read",
       "measurement": "geth.system/disk/readdata.meter",
       "select": [
        [
         { "params": [ "m1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "write",
       "expr": "rate(system_disk_writebytes[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "write",
       "measurement": "geth.system/disk/writedata.meter",
       "select": [
        [
         { "params": [ "m1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "IsValidator",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 272 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_header",
       "measurement": "geth.consensus/isvalidator.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "IsActiveValidator",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 272 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "chain_head_header",
       "measurement": "geth.consensus/isActiveValidator_v2.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Timeout",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
     "targets": [
      {
       "alias": "total timeout count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "geth.consensus/timeoutPoolSize_v2.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "BlockProposed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
     "targets": [
      {
       "alias": "number of proposed blocks",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "geth.consensus/blockProposed_v2.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "ingress",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/InboundTraffic.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "egress",
     "expr": "rate(p2p_egress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "egress",
     "measurement": "geth.p2p/OutboundTraffic.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "peers",
     "expr": "p2p_peers",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "peers",
     "measurement": "geth.p2p/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "dials",
     "expr": "rate(p2p_dials[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "dials",
     "measurement": "geth.p2p/dials.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serves",
     "expr": "rate(p2p_serves[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "serves",
     "measurement": "geth.p2p/serves.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ETH ingress data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "xdcpos handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x00.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x00.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x00.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x01.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x01.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x01.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x02.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x02.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x02.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x03.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x03.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x03.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x04.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x04.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x04.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x05.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x05.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x05.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x06.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x06.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x06.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x07.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x07.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x07.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction announcement",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x08.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x09.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0a.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x0d.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x0d.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0d.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x0e.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x0e.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0e.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x0f.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x0f.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0f.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x10.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x10.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x10.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos vote msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0xe0.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos timeout msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0xe1.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos syncInfo msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0xe2.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ETH egress data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "xdcpos handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x00.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x00.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x00.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x01.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x01.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x01.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x02.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x02.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x02.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x03.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x03.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x03.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x04.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x04.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x04.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x05.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x05.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x05.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x06.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x06.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x06.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x07.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x07.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x07.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction announcement",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x08.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction requests",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x09.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0a.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x0d.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x0d.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0d.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x0e.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x0e.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0e.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x0f.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x0f.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0f.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x10.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x10.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x10.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos vote msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0xe0.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos timeout msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0xe1.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos syncInfo msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0xe2.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ETH egress traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "xdcpos handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x00.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x00.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x00.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x01.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x01.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x01.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x02.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x02.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x02.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x03.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x03.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x03.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x04.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x04.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x04.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x05.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x05.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x05.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x06.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x06.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x06.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x07.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x07.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x07.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction announcement",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x08.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction requests",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x09.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0a.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x0d.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x0d.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0d.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x0e.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x0e.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0e.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x0f.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x0f.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x0f.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0x10.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/64/0x10.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/63/0x10.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos vote msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0xe0.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos timeout msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0xe1.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos syncInfo msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/egress/eth/100/0xe2.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ETH ingress traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "xdcpos handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x00.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x00.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 handshake",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x00.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x01.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x01.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 new block hash",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x01.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x02.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x02.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction broadcast",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x02.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x03.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x03.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x03.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x04.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x04.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block header response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x04.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x05.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x05.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x05.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x06.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x06.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block body response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x06.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x07.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x07.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 block propagation",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x07.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction announcement",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x08.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x09.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 transaction response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0a.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x0d.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x0d.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0d.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x0e.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x0e.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 state response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0e.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x0f.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x0f.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt request",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x0f.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0x10.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/64 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/64/0x10.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "eth/63 receipt response",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/63/0x10.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos vote msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0xe0.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos timeout msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0xe1.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "xdcpos syncInfo msg",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress/eth/100/0xe2.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header",
     "measurement": "geth.chain/head/header.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 18 },
   "targets": [
    {
     "alias": "header",
     "expr": "chain_head_header",
     "legendFormat": "header",
     "measurement": "geth.chain/head/header.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receipt",
     "expr": "chain_head_receipt",
     "legendFormat": "receipt",
     "measurement": "geth.chain/head/receipt.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "block",
     "expr": "chain_head_block",
     "legendFormat": "block",
     "measurement": "geth.chain/head/block.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Gapped",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued",
     "measurement": "geth.txpool/queued.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Locals",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local",
     "measurement": "geth.txpool/local.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "alias": "slots",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.txpool/slots.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.txpool/pending.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped",
     "expr": "txpool_queued",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped",
     "measurement": "geth.txpool/queued.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "local",
     "expr": "txpool_local",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "local",
     "measurement": "geth.txpool/local.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt",
     "measurement": "geth.chain/head/receipt.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction slots used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local",
     "measurement": "geth.txpool/slots.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block",
     "measurement": "geth.chain/head/block.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.txpool/pending.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "execution (p=$percentile)",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/execution.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "validation (p=$percentile)",
     "expr": "chain_validation{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "validation (q=$quantile)",
     "measurement": "geth.chain/validation.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "commit (p=$percentile)",
     "expr": "chain_write{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "commit (q=$quantile)",
     "measurement": "geth.chain/write.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account read (p=$percentile)",
     "expr": "chain_account_reads{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account read (q=$quantile)",
     "measurement": "geth.chain/account/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account update (p=$percentile)",
     "expr": "chain_account_updates{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account update (q=$quantile)",
     "measurement": "geth.chain/account/updates.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account hash (p=$percentile)",
     "expr": "chain_account_hashes{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account hashe (q=$quantile)",
     "measurement": "geth.chain/account/hashes.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account commit (p=$percentile)",
     "expr": "chain_account_commits{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account commit (q=$quantile)",
     "measurement": "geth.chain/account/commits.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage read (p=$percentile)",
     "expr": "chain_storage_reads{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage read (q=$quantile)",
     "measurement": "geth.chain/storage/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage update (p=$percentile)",
     "expr": "chain_storage_updates{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage update (q=$quantile)",
     "measurement": "geth.chain/storage/updates.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage hash (p=$percentile)",
     "expr": "chain_storage_hashes{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage hashe (q=$quantile)",
     "measurement": "geth.chain/storage/hashes.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage commit (p=$percentile)",
     "expr": "chain_storage_commits{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage commit (q=$quantile)",
     "measurement": "geth.chain/storage/commits.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "snapshot account read (p=$percentile)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.chain/snapshot/account/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "snapshot storage read (p=$percentile)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.chain/snapshot/storage/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "snapshot commit (p=$percentile)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.chain/snapshot/commits.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction processing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "known",
     "expr": "rate(txpool_valid[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "valid",
     "measurement": "geth.txpool/known.meter",
     "query": "SELECT \"m1\" FROM \"geth.txpool/valid.meter\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "valid",
     "expr": "rate(txpool_invalid[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "invalid",
     "measurement": "geth.txpool/valid.meter",
     "query": "SELECT \"m1\" FROM \"geth.txpool/valid.meter\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "invalid",
     "expr": "rate(txpool_underpriced[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "underpriced",
     "measurement": "geth.txpool/invalid.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced",
     "expr": "rate(txpool_pending_discard[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable discard",
     "measurement": "geth.txpool/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable discard",
     "expr": "rate(txpool_pending_replace[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable replace",
     "measurement": "geth.txpool/pending/discard.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable replace",
     "expr": "rate(txpool_pending_ratelimit[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable ratelimit",
     "measurement": "geth.txpool/pending/replace.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable ratelimit",
     "expr": "rate(txpool_pending_nofunds[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable nofunds",
     "measurement": "geth.txpool/pending/ratelimit.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable nofunds",
     "expr": "rate(txpool_queued_discard[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped discard",
     "measurement": "geth.txpool/pending/nofunds.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped discard",
     "expr": "rate(txpool_queued_replace[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped replace",
     "measurement": "geth.txpool/queued/discard.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped replace",
     "expr": "rate(txpool_queued_ratelimit[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped ratelimit",
     "measurement": "geth.txpool/queued/replace.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped ratelimit",
     "expr": "rate(txpool_queued_nofunds[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped nofunds",
     "measurement": "geth.txpool/queued/ratelimit.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped nofunds",
     "expr": "rate(txpool_valid[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "valid",
     "measurement": "geth.txpool/queued/nofunds.meter",
     "query": "SELECT \"m1\" FROM \"geth.txpool/valid.meter\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block propagation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "alias": "ingress announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/prop/announces/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/prop/announces/drop.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "malicious announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/prop/announces/dos.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ingress broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/prop/broadcasts/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/prop/broadcasts/drop.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "malicious broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/prop/broadcasts/dos.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "alias": "ingress announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/known.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "malicious announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/dos.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ingress broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/known.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "otherreject broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/otherreject.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "egress requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/out.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "finished requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/done.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "failed requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/fail.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "timed out requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/timeout.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ingress replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/known.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "otherreject replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/otherreject.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block forwarding",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "alias": "receive to announce",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/announces/out.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receive to broadcast",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/broadcasts/out.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction fetcher peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "alias": "waiting",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/waiting/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "queueing",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/queueing/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetching",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/fetching/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction fetcher hashes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "alias": "waiting",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/waiting/hashes.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "queueing",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/queueing/hashes.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetching",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/fetching/hashes.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Reorg meters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "alias": "reorg add meter",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/add.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "reorg drop meter",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/drop.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Reorg total meters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "alias": "total reorgs",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/executes.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "invalidated transactions",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/invalidTx.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "alias": "goroutine count",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.system/cpu/goroutines.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Eth fetcher filter bodies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "alias": "bodies in",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.eth/fetcher/filter/bodies/in.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "bodies out",
     "expr": "txpool_queued",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped",
     "measurement": "geth.eth/fetcher/filter/bodies/out.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Eth fetcher filter headers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "alias": "headers in",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.eth/fetcher/filter/headers/in.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "headers out",
     "expr": "txpool_queued",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped",
     "measurement": "geth.eth/fetcher/filter/headers/in.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "alias": "leveldb read",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/disk/read.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "leveldb write",
     "expr": "rate(eth_db_chaindata_disk_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb write",
     "measurement": "geth.eth/db/chaindata/disk/write.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient read",
     "expr": "rate(eth_db_chaindata_ancient_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient read",
     "measurement": "geth.eth/db/chaindata/ancient/read.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient write",
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/ancient/write.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction read",
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/input.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction write",
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/output.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "alias": "leveldb read",
     "expr": "eth_db_chaindata_disk_read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/disk/read.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "leveldb write",
     "expr": "eth_db_chaindata_disk_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb write",
     "measurement": "geth.eth/db/chaindata/disk/write.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient read",
     "expr": "eth_db_chaindata_ancient_read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient read",
     "measurement": "geth.eth/db/chaindata/ancient/read.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient write",
     "expr": "eth_db_chaindata_ancient_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/ancient/write.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction read",
     "expr": "eth_db_chaindata_ancient_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/input.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction write",
     "expr": "eth_db_chaindata_ancient_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/output.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Persistent size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "targets": [
    {
     "alias": "leveldb",
     "expr": "eth_db_chaindata_disk_size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb",
     "measurement": "geth.eth/db/chaindata/disk/size.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient",
     "expr": "eth_db_chaindata_ancient_size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient",
     "measurement": "geth.eth/db/chaindata/ancient/size.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compaction time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 451 },
     "targets": [
      {
       "alias": "compaction time",
       "expr": "rate(eth_db_chaindata_disk_read[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "leveldb read",
       "measurement": "geth.eth/db/chaindata/compact/time.meter",
       "select": [
        [
         { "params": [ "m1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Compaction delay",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 451 },
     "targets": [
      {
       "alias": "write delay",
       "expr": "rate(eth_db_chaindata_disk_read[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "leveldb read",
       "measurement": "geth.eth/db/chaindata/compact/writedelay/counter.meter",
       "select": [
        [
         { "params": [ "m1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Compaction Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 451 },
     "targets": [
      {
       "alias": "Memory compaction",
       "expr": "rate(eth_db_chaindata_disk_read[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "leveldb read",
       "measurement": "geth.eth/db/chaindata/compact/memory.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Level0 compaction",
       "expr": "rate(eth_db_chaindata_disk_read[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "leveldb read",
       "measurement": "geth.eth/db/chaindata/compact/level0.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Non Level0 compaction",
       "expr": "rate(eth_db_chaindata_disk_read[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "leveldb read",
       "measurement": "geth.eth/db/chaindata/compact/nonlevel0.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Seek compaction",
       "expr": "rate(eth_db_chaindata_disk_read[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "legendFormat": "leveldb read",
       "measurement": "geth.eth/db/chaindata/compact/seek.gauge",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}