apiVersion: 1

alertmanagerConfigs:
  - orgId: 1
    templates: []
    receivers:
      - name: 'nestjs-backend'
        grafana_managed_receiver_configs:
          - name: 'nestjs-backend'
            type: 'webhook'
            uid: 'webhook-receiver'
            settings:
              url: 'http://xdc-monitor:3000/api/notifications/telegram'
              username: ''
              password: ''
              httpMethod: 'POST'
              maxAlerts: '10'
            disableResolveMessage: false
    route:
      receiver: 'nestjs-backend'
      group_by: ['alertname', 'component']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 5m
      routes:
        - receiver: 'nestjs-backend'
          matchers:
            - name: 'severity'
              value: 'critical'
          group_wait: 0s
          repeat_interval: 1m
        - receiver: 'nestjs-backend'
          matchers:
            - name: 'component'
              value: 'rpc'
          group_wait: 5s
          repeat_interval: 3m
