apiVersion: 1

alertmanagerConfigs:
  - orgId: 1
    templates: []
    receivers:
      - name: 'nestjs-backend'
        grafana_managed_receiver_configs:
          - name: 'nestjs-backend'
            type: 'webhook'
            uid: 'webhook-receiver'
            settings:
              url: 'http://xdc-monitor:3000/api/notifications/telegram'
              username: ''
              password: ''
              httpMethod: 'POST'
              maxAlerts: '10'
            disableResolveMessage: false
    route:
      receiver: 'nestjs-backend'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      routes: []
