name: Deploy to Staging

on:
  workflow_run:
    workflows: ['XDC Monitor CI']
    branches: [staging]
    types: [completed]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Manual SSH setup
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_KEY }}
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
          STAGING_USER: ${{ secrets.STAGING_USER }}
        run: |
          # Debug environment
          echo "Current user: $(whoami)"
          echo "Home directory: $HOME"

          # Create SSH directory using absolute path
          SSH_DIR="${HOME}/.ssh"
          echo "Creating SSH directory: ${SSH_DIR}"
          mkdir -p "${SSH_DIR}"
          chmod 700 "${SSH_DIR}"
          echo "SSH directory created - checking existence:"
          ls -la "${HOME}/" | grep .ssh

          # Verify directory exists before proceeding
          if [ ! -d "${SSH_DIR}" ]; then
            echo "ERROR: SSH directory creation failed!"
            exit 1
          fi

          # Write the private key to a file
          KEY_FILE="${SSH_DIR}/id_ed25519"
          echo "Writing SSH key to file: ${KEY_FILE}"
          echo "$SSH_PRIVATE_KEY" > "${KEY_FILE}"
          chmod 600 "${KEY_FILE}"
          echo "SSH key file created:"
          ls -la "${SSH_DIR}" || echo "Failed to list SSH directory"

          # Start the SSH agent manually
          echo "Starting SSH agent..."
          eval "$(ssh-agent -s)"

          # Check if key file exists and has content
          if [ -s "${KEY_FILE}" ]; then
            echo "SSH key file exists and has content"
          else
            echo "ERROR: SSH key file is empty or doesn't exist"
            ls -la "${SSH_DIR}"
          fi

          ssh-add "${KEY_FILE}" || echo "Failed to add key to agent: $?"

          # Validate key format
          echo "Validating SSH key format..."
          ssh-keygen -l -f "${KEY_FILE}" && echo "Key format appears valid" || echo "Key format invalid"

          # Show beginning of key (safely)
          echo "Key begins with:"
          head -n 1 "${KEY_FILE}"
          echo "Key ends with:"
          tail -n 1 "${KEY_FILE}"
          echo "Key length in bytes:"
          wc -c "${KEY_FILE}"
          echo "Line count:"
          wc -l "${KEY_FILE}"

          # Additional validation
          if grep -q "BEGIN .* PRIVATE KEY" "${KEY_FILE}"; then
            echo "Key has proper header"
          else
            echo "ERROR: Key lacks proper header!"
          fi

          if grep -q "END .* PRIVATE KEY" "${KEY_FILE}"; then
            echo "Key has proper footer"
          else
            echo "ERROR: Key lacks proper footer!"
          fi

          # Setup SSH config to use the correct port and skip host checking
          echo "Host $STAGING_HOST" > "${SSH_DIR}/config"
          echo "    User $STAGING_USER" >> "${SSH_DIR}/config"
          echo "    Port 1122" >> "${SSH_DIR}/config"
          echo "    StrictHostKeyChecking no" >> "${SSH_DIR}/config"
          echo "    UserKnownHostsFile=/dev/null" >> "${SSH_DIR}/config"
          echo "    LogLevel DEBUG3" >> "${SSH_DIR}/config"
          chmod 600 "${SSH_DIR}/config"

          # Debug information
          echo "SSH key loaded. Checking connection..."
          echo "SSH config file:"
          cat "${SSH_DIR}/config"

          # List keys in agent
          echo "Keys in agent:"
          ssh-add -l || echo "No keys in agent"

          # Test the connection with full debugging
          echo "Testing SSH connection to $STAGING_HOST:1122..."
          ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $STAGING_HOST "echo 'SSH CONNECTION SUCCESSFUL'" || {
            echo "Connection failed with code $?"
            echo "Testing basic connectivity with nc:"
            which nc && nc -zv $STAGING_HOST 1122 || echo "netcat not available"
          }

      - name: Deploy to staging server
        env:
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
          STAGING_USER: ${{ secrets.STAGING_USER }}
          DEPLOY_PATH: ${{ secrets.STAGING_DEPLOY_PATH || '/home/deploy/xdc-monitor' }}
          INFLUXDB_TOKEN: ${{ secrets.STAGING_INFLUXDB_TOKEN }}
          INFLUXDB_ORG: ${{ secrets.STAGING_INFLUXDB_ORG }}
          INFLUXDB_BUCKET: ${{ secrets.STAGING_INFLUXDB_BUCKET }}
          INFLUXDB_ADMIN_USER: ${{ secrets.STAGING_INFLUXDB_ADMIN_USER }}
          INFLUXDB_ADMIN_PASSWORD: ${{ secrets.STAGING_INFLUXDB_ADMIN_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.STAGING_TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.STAGING_TELEGRAM_CHAT_ID }}
          GRAFANA_ADMIN_USER: ${{ secrets.STAGING_GRAFANA_ADMIN_USER }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.STAGING_GRAFANA_ADMIN_PASSWORD }}
        run: |
          echo "Connecting to staging server..."
          # Using SSH config for simplicity - all options are defined there
          ssh $STAGING_HOST "mkdir -p $DEPLOY_PATH"

          echo "Copying deployment files..."
          scp docker-compose.yml $STAGING_HOST:$DEPLOY_PATH/
          scp run.sh $STAGING_HOST:$DEPLOY_PATH/

          echo "Generating .env file with secrets..."
          cat > env_staging << EOF
          SCAN_INTERVAL=15

          # Monitoring configuration
          ENABLE_RPC_MONITORING=true
          ENABLE_PORT_MONITORING=true
          ENABLE_BLOCK_MONITORING=true
          BLOCK_TIME_THRESHOLD=3.0

          # Alert configuration
          ENABLE_DASHBOARD_ALERTS=true
          ENABLE_CHAT_NOTIFICATIONS=true
          NOTIFICATION_WEBHOOK_URL=

          # Telegram notification configuration
          TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}"
          TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID}"

          # Logging configuration
          LOG_LEVEL=info

          # InfluxDB Configuration
          INFLUXDB_URL=http://localhost:8086
          INFLUXDB_TOKEN="${INFLUXDB_TOKEN}"
          INFLUXDB_ORG="${INFLUXDB_ORG}"
          INFLUXDB_BUCKET="${INFLUXDB_BUCKET}"
          INFLUXDB_ADMIN_USER="${INFLUXDB_ADMIN_USER}"
          INFLUXDB_ADMIN_PASSWORD="${INFLUXDB_ADMIN_PASSWORD}"

          # Grafana Admin Credentials
          GRAFANA_ADMIN_USER="${GRAFANA_ADMIN_USER}"
          GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD}"
          EOF

          echo "Copying the generated .env file to staging server..."
          scp env_staging $STAGING_HOST:$DEPLOY_PATH/.env
          echo "Removing the local copy for security..."
          rm env_staging

          echo "Pulling latest images and restarting services..."
          ssh $STAGING_HOST "cd $DEPLOY_PATH && docker-compose pull && ./run.sh rebuild"

          echo "Deployment to staging completed successfully!"
